// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repo_Into_Graph_DataAccess.Database;

#nullable disable

namespace Repo_Into_Graph_DataAccess.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20260620031858_UpdateFeatureMethodMapping")]
    partial class UpdateFeatureMethodMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Analysis.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("RepoDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RepoLanguage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RepoName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RepoOwner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("RepoStars")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RepoUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RepoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("analysis_runs", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Business.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("businesses", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Business.FeatureBusinessMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("FeatureId");

                    b.ToTable("feature_business_mappings", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.CallGraphEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("CalleeClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CalleeMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallerClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallerMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("call_graph_edges", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Feature.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataFlowMermaidGraph")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntryPoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MermaidGraph")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("features", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Feature.FeatureMethodMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MappedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MethodSourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("MethodSourceId");

                    b.ToTable("feature_method_mappings", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Feature.FeatureStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalleeClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CalleeMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallerClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallerMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("feature_steps", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.FewShot.FewShotExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuggestedAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Difficulty");

                    b.ToTable("few_shot_examples", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Method.MethodSourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("method_sources", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Business.Business", b =>
                {
                    b.HasOne("Repo_Into_Graph_DataAccess.Models.Analysis.AnalysisRun", "AnalysisRun")
                        .WithMany("Businesses")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Business.FeatureBusinessMapping", b =>
                {
                    b.HasOne("Repo_Into_Graph_DataAccess.Models.Business.Business", "Business")
                        .WithMany("FeatureBusinessMappings")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repo_Into_Graph_DataAccess.Models.Feature.Feature", "Feature")
                        .WithMany("FeatureBusinessMappings")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.CallGraphEdge", b =>
                {
                    b.HasOne("Repo_Into_Graph_DataAccess.Models.Analysis.AnalysisRun", "AnalysisRun")
                        .WithMany("CallGraphEdges")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Feature.Feature", b =>
                {
                    b.HasOne("Repo_Into_Graph_DataAccess.Models.Analysis.AnalysisRun", "AnalysisRun")
                        .WithMany("Features")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Feature.FeatureMethodMapping", b =>
                {
                    b.HasOne("Repo_Into_Graph_DataAccess.Models.Feature.Feature", "Feature")
                        .WithMany("FeatureMethodMappings")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repo_Into_Graph_DataAccess.Models.Method.MethodSourceRecord", "MethodSource")
                        .WithMany("FeatureMethodMappings")
                        .HasForeignKey("MethodSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("MethodSource");
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Feature.FeatureStep", b =>
                {
                    b.HasOne("Repo_Into_Graph_DataAccess.Models.Feature.Feature", "Feature")
                        .WithMany("Steps")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Method.MethodSourceRecord", b =>
                {
                    b.HasOne("Repo_Into_Graph_DataAccess.Models.Analysis.AnalysisRun", "AnalysisRun")
                        .WithMany("MethodSources")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Analysis.AnalysisRun", b =>
                {
                    b.Navigation("Businesses");

                    b.Navigation("CallGraphEdges");

                    b.Navigation("Features");

                    b.Navigation("MethodSources");
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Business.Business", b =>
                {
                    b.Navigation("FeatureBusinessMappings");
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Feature.Feature", b =>
                {
                    b.Navigation("FeatureBusinessMappings");

                    b.Navigation("FeatureMethodMappings");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Repo_Into_Graph_DataAccess.Models.Method.MethodSourceRecord", b =>
                {
                    b.Navigation("FeatureMethodMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
