// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repo_Into_Graph.Data;

#nullable disable

namespace Repo_Into_Graph.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20260608112854_InitialCreate1")]
    partial class InitialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Repo_Into_Graph.Data.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("analysis_runs", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Data.CallGraphEdgeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("CalleeClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CalleeMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallerClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallerMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("call_graph_edges", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Data.FeatureRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("feature_records", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Data.MethodSourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("method_sources", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Data.FeatureMethodMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MappedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MethodSourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("MethodSourceId");

                    b.ToTable("feature_method_mappings", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Data.CallGraphEdgeRecord", b =>
                {
                    b.HasOne("Repo_Into_Graph.Data.AnalysisRun", "AnalysisRun")
                        .WithMany("CallGraphEdges")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Repo_Into_Graph.Data.FeatureRecord", b =>
                {
                    b.HasOne("Repo_Into_Graph.Data.AnalysisRun", "AnalysisRun")
                        .WithMany("Features")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Repo_Into_Graph.Data.MethodSourceRecord", b =>
                {
                    b.HasOne("Repo_Into_Graph.Data.AnalysisRun", "AnalysisRun")
                        .WithMany("MethodSources")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Data.FeatureMethodMapping", b =>
                {
                    b.HasOne("Repo_Into_Graph.Data.FeatureRecord", "Feature")
                        .WithMany("FeatureMethodMappings")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repo_Into_Graph.Data.MethodSourceRecord", "MethodSource")
                        .WithMany("FeatureMethodMappings")
                        .HasForeignKey("MethodSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("MethodSource");
                });

            modelBuilder.Entity("Repo_Into_Graph.Data.AnalysisRun", b =>
                {
                    b.Navigation("CallGraphEdges");

                    b.Navigation("Features");

                    b.Navigation("MethodSources");
                });

            modelBuilder.Entity("Repo_Into_Graph.Data.FeatureRecord", b =>
                {
                    b.Navigation("FeatureMethodMappings");
                });

            modelBuilder.Entity("Repo_Into_Graph.Data.MethodSourceRecord", b =>
                {
                    b.Navigation("FeatureMethodMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
