using Repo_Into_Graph_DataAccess.Database;
// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Repo_Into_Graph.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20260616043139_AddFewShotExamples")]
    partial class AddFewShotExamples
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Repo_Into_Graph.Models.CallGraphEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("CalleeClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CalleeMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallerClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallerMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("call_graph_edges", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.Analysis.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("analysis_runs", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.BusinessFlows.BusinessFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EntryPoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MermaidGraph")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("business_flows", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.BusinessFlows.BusinessFlowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessFlowId")
                        .HasColumnType("uuid");

                    b.Property<string>("CalleeClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CalleeMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallerClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallerMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessFlowId");

                    b.ToTable("business_flow_steps", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.Feature.FeatureMethodMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MappedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MethodSourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("MethodSourceId");

                    b.ToTable("feature_method_mappings", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.Feature.FeatureRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("feature_records", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.FewShot.FewShotExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuggestedAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Difficulty");

                    b.ToTable("few_shot_examples", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.Method.MethodSourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("method_sources", (string)null);
                });

            modelBuilder.Entity("Repo_Into_Graph.Models.CallGraphEdge", b =>
                {
                    b.HasOne("Repo_Into_Graph.Repo_Into_Graph.Models.Analysis.AnalysisRun", "AnalysisRun")
                        .WithMany("CallGraphEdges")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.BusinessFlows.BusinessFlow", b =>
                {
                    b.HasOne("Repo_Into_Graph.Repo_Into_Graph.Models.Analysis.AnalysisRun", "AnalysisRun")
                        .WithMany("BusinessFlows")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.BusinessFlows.BusinessFlowStep", b =>
                {
                    b.HasOne("Repo_Into_Graph.Repo_Into_Graph.Models.BusinessFlows.BusinessFlow", "BusinessFlow")
                        .WithMany("Steps")
                        .HasForeignKey("BusinessFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessFlow");
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.Feature.FeatureMethodMapping", b =>
                {
                    b.HasOne("Repo_Into_Graph.Repo_Into_Graph.Models.Feature.FeatureRecord", "Feature")
                        .WithMany("FeatureMethodMappings")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repo_Into_Graph.Repo_Into_Graph.Models.Method.MethodSourceRecord", "MethodSource")
                        .WithMany("FeatureMethodMappings")
                        .HasForeignKey("MethodSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("MethodSource");
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.Feature.FeatureRecord", b =>
                {
                    b.HasOne("Repo_Into_Graph.Repo_Into_Graph.Models.Analysis.AnalysisRun", "AnalysisRun")
                        .WithMany("Features")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.Method.MethodSourceRecord", b =>
                {
                    b.HasOne("Repo_Into_Graph.Repo_Into_Graph.Models.Analysis.AnalysisRun", "AnalysisRun")
                        .WithMany("MethodSources")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.Analysis.AnalysisRun", b =>
                {
                    b.Navigation("BusinessFlows");

                    b.Navigation("CallGraphEdges");

                    b.Navigation("Features");

                    b.Navigation("MethodSources");
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.BusinessFlows.BusinessFlow", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.Feature.FeatureRecord", b =>
                {
                    b.Navigation("FeatureMethodMappings");
                });

            modelBuilder.Entity("Repo_Into_Graph.Repo_Into_Graph.Models.Method.MethodSourceRecord", b =>
                {
                    b.Navigation("FeatureMethodMappings");
                });
#pragma warning restore 612, 618
        }
    }
}



